### ISSUE TITLE
Github actions integration doesn't work

### ISSUE THREAD

**Issue by mayk0gan** [akaihola/darker#253]
Using the exact example from the README file, I receive: 

```
Prepare all required actions
Getting action download info
Error: Unable to resolve action `akaihola/darker@1.4.0`, unable to find version `1.4.0`
```

I've tried to change the version 1.3.2 (and some additional ones) and got:
```
Download action repository 'actions/checkout@v2' (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)
Download action repository 'akaihola/darker@1.3.2' (SHA:67ca4ae1bdb9e7f832f7bb932a683496e70c4faa)
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/akaihola/darker/1.3.2'. Did you forget to run actions/checkout before running your local action?
```

**Comment by akaihola** [comment]
Version 1.4.0 hasn't yet been released, so that's not supposed to work.

Version 1.3.2 didn't have GitHub Actions support yet.

So the only thing that could work right now is `akaihola/darker@master`.

Sorry for the confusion, I was anticipating to release 1.4.0 very soon after merging this feature, but it got delayed by life. So this will be fixed once 1.4.0 is released.
